### PR TITLE
Add `suppressConflictError` option

### LINKED ISSUE #17: Handle already existing release hash
As discussed in https://github.com/40thieves/webpack-sentry-plugin/issues/16#issuecomment-289450544, currently creation of releases will crash if the release hash stays the same.

Potential options:

1. Crash with better error message
2. Overwrite the existing release's files (how does Sentry api handle this?)
3. Delete the existing release and try again

### PR DESCRIPTION
**Pull request by rhys-vdw**
Allow conflict errors to be suppressed, but still fail build on all other errors.

Closes #17

### CODE REVIEW

**Comment by rhys-vdw** [comment]
I haven't added a test for this, but I can add one if you approve the change.

Manual testing appears to work:

```
remote:        WARNING in Sentry Plugin: StatusCodeError: 409 - "{\"detail\": \"A file matching this name already exists for the given release\"}"
```

**Comment by fritx** [comment]
@rhys-vdw what are the other errors?

**Comment by rhys-vdw** [comment]
@fritx ah, haven't experienced any specifically, but presumably auth failures, incorrect org/project, timeout/connectivity errors and any possible upstream 500 errors.

**Comment by fritx** [comment]
@rhys-vdw cool +1

**Comment by rhys-vdw** [comment]
@40thieves is there any intention to continue maintaining this repository? If not would you prefer a community fork, or to take on other collaborators?

**Comment by 40thieves** [comment]
Hi. Thanks for the contribution.

Sorry about the huge delay. To be honest I've been quite burned out on this and other projects so I haven't been keeping up with them. Apologies again

**Comment by 40thieves** [comment]
@rhys-vdw Apologies again. I would be open to collaborators if there's any volunteers. I'll open an issue

**Comment by rhys-vdw** [comment]
> To be honest I've been quite burned out on this and other projects so I haven't been keeping up with them. Apologies again

All good dude. Been there before. Thanks for the merge. I'd be happy to collaborate, but my minimum input will be just fixing things that are affecting us in production and the occasional response to an issue that sticks out in my inbox.

**Pull request merged**
